[prompt]
search_placeholder_text = "（输入以搜索）"
more_choices_text = "（上下移动以显示更多选项）"

generate_new_config = "将会生成新配置文件……\n"

welcome = "欢迎使用[gold1]群星科技关联生成器[/]！"
read_instructions = "请仔细[cyan]阅读说明[/]！"
pause = "请按[cyan]回车键[/]继续……"

ask_game_path = "[white]你的[cyan]游戏路径[/]是？[/]"
ask_document_path = "[white]你的[cyan]文档路径[/]是？[/]"
config_created = "[green]配置文件创建成功！[/]"

close_launcher = "在继续之前，请[cyan]关闭启动器[/]"
confirm_use_saved_vanilla = "是否使用[yellow]原版游戏[/]与输出路径 [yellow]{1}[/]？"
confirm_use_saved_target = "是否使用已保存的播放集 [yellow]{0}[/] 与目标模组 [yellow]{1}[/]？"
choose_playset = "选择目标播放集（按 [cyan]Esc[/] 使用原版游戏）"
current_playset_prefix = "[green]（当前）[/] "
ask_output_path = "生成的文件的输出路径是？"
choose_target_mod = "选择用于输出的生成文件的目标模组"
colliding_target_mod_list_header = "以下是这些模组的路径："
colliding_target_mod_list_item = "  - {0}"
confirm_save_vanilla = "是否保存选择？（[yellow]原版游戏[/]，输出路径：[yellow]{1}[/]）？"
confirm_save_target = "是否保存选择？（播放集：[yellow]{0}[/] ，目标模组：[yellow]{1}[/]）？"

saved_localization = "已将 [cyan]{0}[/] 个本地化文件写入到 [grey underline]{1}[/]"
generation_summary = "[green]成功为 [cyan]{1}[/] 个科技生成 [cyan]{0}[/] 条关联条目！[/]"

[progress]
connecting_launcher_db = "正在连接启动器数据库"
loading_game = "正在加载游戏（CWTools）"
loading_scripted_variables = "正在加载脚本变量"
loading_authority_suffixes = "正在加载政体后缀"
loading_technologies = "正在加载科技"
building_tech_relationship = "正在构建科技关系"
loading_localization = "正在加载本地化"
generating_localization = "正在生成本地化"
writing_localization_fragments = "正在写入本地化片段"
writing_localization = "正在写入本地化"

[data]
localization_entry_not_found = "未找到科技 {0} 的本地化条目"
localization_entry_and_swap_not_found = "未找到科技 {0} 与其替换科技 {1} 的本地化条目"
tech_unknown_prereq = "科技 {0} 有未知的前置科技：{1}"
tech_unnamed_swap = "科技 {0} 有未命名的替换科技，已跳过"

[update]
new_version_found = "[gold1]发现新版本！[link={0}]{1}[/]（{2:g}）[/]"
release_body = "[grey]{0}[/]"

[error]
config_parse_failed = "配置文件解析失败："
playset_not_found = "未找到播放集！"
target_mod_not_found = "未找到目标模组！"
multiple_mods_same_name = "检测到多个同名模组"
