// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;

using StlTechRelGen.Db;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(LauncherV2DbContext), typeof(LauncherV2DbContextModel))]
