// <auto-generated />
using System;

using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace StlTechRelGen.Db;

public partial class LauncherV2DbContextModel {
	private LauncherV2DbContextModel()
		: base(skipDetectChanges: false, modelId: new Guid("30bafaac-0a28-4330-9d75-13f899d0b33c"), entityTypeCount: 3) {
	}

	partial void Initialize() {
		var mod = ModEntityType.Create(this);
		var playset = PlaysetEntityType.Create(this);
		var playsetsMod = PlaysetsModEntityType.Create(this);

		PlaysetsModEntityType.CreateForeignKey1(playsetsMod, mod);
		PlaysetsModEntityType.CreateForeignKey2(playsetsMod, playset);

		ModEntityType.CreateAnnotations(mod);
		PlaysetEntityType.CreateAnnotations(playset);
		PlaysetsModEntityType.CreateAnnotations(playsetsMod);

		AddAnnotation("ProductVersion", "10.0.9");
	}
}
