// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace StlTechRelGen.Db;

[DbContext(typeof(LauncherV2DbContext))]
public partial class LauncherV2DbContextModel : RuntimeModel {
	private static readonly bool _useOldBehavior31751 =
		System.AppContext.TryGetSwitch("Microsoft.EntityFrameworkCore.Issue31751", out var enabled31751) && enabled31751;

	static LauncherV2DbContextModel() {
		var model = new LauncherV2DbContextModel();

		if (_useOldBehavior31751) {
			model.Initialize();
		} else {
			var thread = new System.Threading.Thread(RunInitialization, 10 * 1024 * 1024);
			thread.Start();
			thread.Join();

			void RunInitialization() {
				model.Initialize();
			}
		}

		model.Customize();
		_instance = (LauncherV2DbContextModel) model.FinalizeModel();
	}

	private static LauncherV2DbContextModel _instance;
	public static IModel Instance => _instance;

	partial void Initialize();

	partial void Customize();
}
