// <auto-generated />
using System;
using System.Reflection;

using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace StlTechRelGen.Db;

[EntityFrameworkInternal]
public partial class ModEntityType {
	public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null) {
		var runtimeEntityType = model.AddEntityType(
			"StlTechRelGen.Db.Mod",
			typeof(Mod),
			baseEntityType,
			propertyCount: 39,
			keyCount: 1);

		var id = runtimeEntityType.AddProperty(
			"Id",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			afterSaveBehavior: PropertySaveBehavior.Throw);
		id.AddAnnotation("Relational:ColumnName", "id");
		id.AddAnnotation("Relational:ColumnType", "char(36)");

		var arch = runtimeEntityType.AddProperty(
			"Arch",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("Arch", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<Arch>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		arch.AddAnnotation("Relational:ColumnName", "arch");

		var archivePath = runtimeEntityType.AddProperty(
			"ArchivePath",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("ArchivePath", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<ArchivePath>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		archivePath.AddAnnotation("Relational:ColumnName", "archivePath");

		var cause = runtimeEntityType.AddProperty(
			"Cause",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("Cause", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<Cause>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true,
			valueGenerated: ValueGenerated.OnAdd);
		cause.AddAnnotation("Relational:ColumnName", "cause");
		cause.AddAnnotation("Relational:DefaultValueSql", "null");

		var createdDate = runtimeEntityType.AddProperty(
			"CreatedDate",
			typeof(int?),
			propertyInfo: typeof(Mod).GetProperty("CreatedDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<CreatedDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		createdDate.AddAnnotation("Relational:ColumnName", "createdDate");
		createdDate.AddAnnotation("Relational:ColumnType", "datetime");

		var descriptionDeprecated = runtimeEntityType.AddProperty(
			"DescriptionDeprecated",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("DescriptionDeprecated", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<DescriptionDeprecated>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		descriptionDeprecated.AddAnnotation("Relational:ColumnName", "descriptionDeprecated");

		var descriptionPdx = runtimeEntityType.AddProperty(
			"DescriptionPdx",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("DescriptionPdx", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<DescriptionPdx>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		descriptionPdx.AddAnnotation("Relational:ColumnName", "descriptionPdx");
		descriptionPdx.AddAnnotation("Relational:ColumnType", "varchar(255)");

		var descriptionSteam = runtimeEntityType.AddProperty(
			"DescriptionSteam",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("DescriptionSteam", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<DescriptionSteam>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		descriptionSteam.AddAnnotation("Relational:ColumnName", "descriptionSteam");
		descriptionSteam.AddAnnotation("Relational:ColumnType", "varchar(255)");

		var dirPath = runtimeEntityType.AddProperty(
			"DirPath",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("DirPath", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<DirPath>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		dirPath.AddAnnotation("Relational:ColumnName", "dirPath");

		var displayName = runtimeEntityType.AddProperty(
			"DisplayName",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("DisplayName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<DisplayName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		displayName.AddAnnotation("Relational:ColumnName", "displayName");
		displayName.AddAnnotation("Relational:ColumnType", "varchar(255)");

		var gameRegistryId = runtimeEntityType.AddProperty(
			"GameRegistryId",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("GameRegistryId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<GameRegistryId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		gameRegistryId.AddAnnotation("Relational:ColumnName", "gameRegistryId");

		var isMetadataApplied = runtimeEntityType.AddProperty(
			"IsMetadataApplied",
			typeof(bool?),
			propertyInfo: typeof(Mod).GetProperty("IsMetadataApplied", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<IsMetadataApplied>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			valueGenerated: ValueGenerated.OnAdd);
		isMetadataApplied.AddAnnotation("Relational:ColumnName", "isMetadataApplied");
		isMetadataApplied.AddAnnotation("Relational:ColumnType", "boolean");
		isMetadataApplied.AddAnnotation("Relational:DefaultValueSql", "'0'");

		var isNew = runtimeEntityType.AddProperty(
			"IsNew",
			typeof(bool?),
			propertyInfo: typeof(Mod).GetProperty("IsNew", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<IsNew>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		isNew.AddAnnotation("Relational:ColumnName", "isNew");
		isNew.AddAnnotation("Relational:ColumnType", "boolean");

		var keepLatest = runtimeEntityType.AddProperty(
			"KeepLatest",
			typeof(bool?),
			propertyInfo: typeof(Mod).GetProperty("KeepLatest", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<KeepLatest>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			valueGenerated: ValueGenerated.OnAdd);
		keepLatest.AddAnnotation("Relational:ColumnName", "keepLatest");
		keepLatest.AddAnnotation("Relational:ColumnType", "boolean");
		keepLatest.AddAnnotation("Relational:DefaultValueSql", "'1'");

		var metadataGameId = runtimeEntityType.AddProperty(
			"MetadataGameId",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("MetadataGameId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<MetadataGameId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		metadataGameId.AddAnnotation("Relational:ColumnName", "metadataGameId");
		metadataGameId.AddAnnotation("Relational:ColumnType", "varchar(255)");

		var metadataId = runtimeEntityType.AddProperty(
			"MetadataId",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("MetadataId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<MetadataId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		metadataId.AddAnnotation("Relational:ColumnName", "metadataId");
		metadataId.AddAnnotation("Relational:ColumnType", "varchar(255)");

		var metadataStatus = runtimeEntityType.AddProperty(
			"MetadataStatus",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("MetadataStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<MetadataStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			valueGenerated: ValueGenerated.OnAdd);
		metadataStatus.AddAnnotation("Relational:ColumnName", "metadataStatus");
		metadataStatus.AddAnnotation("Relational:DefaultValue", "not_applied");

		var metadataVersion = runtimeEntityType.AddProperty(
			"MetadataVersion",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("MetadataVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<MetadataVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		metadataVersion.AddAnnotation("Relational:ColumnName", "metadataVersion");
		metadataVersion.AddAnnotation("Relational:ColumnType", "varchar(255)");

		var name = runtimeEntityType.AddProperty(
			"Name",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		name.AddAnnotation("Relational:ColumnName", "name");
		name.AddAnnotation("Relational:ColumnType", "varchar(255)");

		var os = runtimeEntityType.AddProperty(
			"Os",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("Os", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<Os>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		os.AddAnnotation("Relational:ColumnName", "os");

		var pdxId = runtimeEntityType.AddProperty(
			"PdxId",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("PdxId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<PdxId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		pdxId.AddAnnotation("Relational:ColumnName", "pdxId");
		pdxId.AddAnnotation("Relational:ColumnType", "varchar(255)");

		var remotePdxId = runtimeEntityType.AddProperty(
			"RemotePdxId",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("RemotePdxId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<RemotePdxId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		remotePdxId.AddAnnotation("Relational:ColumnName", "remotePdxId");
		remotePdxId.AddAnnotation("Relational:ColumnType", "varchar(255)");

		var remotePdxUserId = runtimeEntityType.AddProperty(
			"RemotePdxUserId",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("RemotePdxUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<RemotePdxUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		remotePdxUserId.AddAnnotation("Relational:ColumnName", "remotePdxUserId");
		remotePdxUserId.AddAnnotation("Relational:ColumnType", "varchar(255)");

		var remoteSteamId = runtimeEntityType.AddProperty(
			"RemoteSteamId",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("RemoteSteamId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<RemoteSteamId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		remoteSteamId.AddAnnotation("Relational:ColumnName", "remoteSteamId");
		remoteSteamId.AddAnnotation("Relational:ColumnType", "varchar(255)");

		var remoteSteamUserId = runtimeEntityType.AddProperty(
			"RemoteSteamUserId",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("RemoteSteamUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<RemoteSteamUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		remoteSteamUserId.AddAnnotation("Relational:ColumnName", "remoteSteamUserId");
		remoteSteamUserId.AddAnnotation("Relational:ColumnType", "varchar(255)");

		var repositoryPath = runtimeEntityType.AddProperty(
			"RepositoryPath",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("RepositoryPath", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<RepositoryPath>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		repositoryPath.AddAnnotation("Relational:ColumnName", "repositoryPath");

		var requiredVersion = runtimeEntityType.AddProperty(
			"RequiredVersion",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("RequiredVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<RequiredVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		requiredVersion.AddAnnotation("Relational:ColumnName", "requiredVersion");
		requiredVersion.AddAnnotation("Relational:ColumnType", "varchar(255)");

		var shortDescriptionPdx = runtimeEntityType.AddProperty(
			"ShortDescriptionPdx",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("ShortDescriptionPdx", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<ShortDescriptionPdx>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		shortDescriptionPdx.AddAnnotation("Relational:ColumnName", "shortDescriptionPdx");
		shortDescriptionPdx.AddAnnotation("Relational:ColumnType", "varchar(255)");

		var size = runtimeEntityType.AddProperty(
			"Size",
			typeof(long?),
			propertyInfo: typeof(Mod).GetProperty("Size", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<Size>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		size.AddAnnotation("Relational:ColumnName", "size");

		var source = runtimeEntityType.AddProperty(
			"Source",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("Source", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<Source>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
		source.AddAnnotation("Relational:ColumnName", "source");

		var status = runtimeEntityType.AddProperty(
			"Status",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
		status.AddAnnotation("Relational:ColumnName", "status");

		var steamId = runtimeEntityType.AddProperty(
			"SteamId",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("SteamId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<SteamId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		steamId.AddAnnotation("Relational:ColumnName", "steamId");
		steamId.AddAnnotation("Relational:ColumnType", "varchar(255)");

		var subscribedDate = runtimeEntityType.AddProperty(
			"SubscribedDate",
			typeof(int?),
			propertyInfo: typeof(Mod).GetProperty("SubscribedDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<SubscribedDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		subscribedDate.AddAnnotation("Relational:ColumnName", "subscribedDate");
		subscribedDate.AddAnnotation("Relational:ColumnType", "datetime");

		var tags = runtimeEntityType.AddProperty(
			"Tags",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("Tags", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<Tags>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true,
			valueGenerated: ValueGenerated.OnAdd);
		tags.AddAnnotation("Relational:ColumnName", "tags");
		tags.AddAnnotation("Relational:ColumnType", "json");
		tags.AddAnnotation("Relational:DefaultValue", "[]");

		var thumbnailPath = runtimeEntityType.AddProperty(
			"ThumbnailPath",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("ThumbnailPath", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<ThumbnailPath>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		thumbnailPath.AddAnnotation("Relational:ColumnName", "thumbnailPath");

		var thumbnailUrl = runtimeEntityType.AddProperty(
			"ThumbnailUrl",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("ThumbnailUrl", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<ThumbnailUrl>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		thumbnailUrl.AddAnnotation("Relational:ColumnName", "thumbnailUrl");

		var timeUpdated = runtimeEntityType.AddProperty(
			"TimeUpdated",
			typeof(int?),
			propertyInfo: typeof(Mod).GetProperty("TimeUpdated", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<TimeUpdated>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		timeUpdated.AddAnnotation("Relational:ColumnName", "timeUpdated");

		var userVersion = runtimeEntityType.AddProperty(
			"UserVersion",
			typeof(bool?),
			propertyInfo: typeof(Mod).GetProperty("UserVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<UserVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true,
			valueGenerated: ValueGenerated.OnAdd);
		userVersion.AddAnnotation("Relational:ColumnName", "userVersion");
		userVersion.AddAnnotation("Relational:ColumnType", "boolean");
		userVersion.AddAnnotation("Relational:DefaultValueSql", "null");

		var version = runtimeEntityType.AddProperty(
			"Version",
			typeof(string),
			propertyInfo: typeof(Mod).GetProperty("Version", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Mod).GetField("<Version>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		version.AddAnnotation("Relational:ColumnName", "version");
		version.AddAnnotation("Relational:ColumnType", "varchar(255)");

		var key = runtimeEntityType.AddKey(
			new[] { id });
		runtimeEntityType.SetPrimaryKey(key);

		return runtimeEntityType;
	}

	public static void CreateAnnotations(RuntimeEntityType runtimeEntityType) {
		runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
		runtimeEntityType.AddAnnotation("Relational:Schema", null);
		runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
		runtimeEntityType.AddAnnotation("Relational:TableName", "mods");
		runtimeEntityType.AddAnnotation("Relational:ViewName", null);
		runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

		Customize(runtimeEntityType);
	}

	static partial void Customize(RuntimeEntityType runtimeEntityType);
}
