// <auto-generated />
using System;
using System.Reflection;

using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace StlTechRelGen.Db;

[EntityFrameworkInternal]
public partial class PlaysetEntityType {
	public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null) {
		var runtimeEntityType = model.AddEntityType(
			"StlTechRelGen.Db.Playset",
			typeof(Playset),
			baseEntityType,
			propertyCount: 21,
			unnamedIndexCount: 1,
			keyCount: 1);

		var id = runtimeEntityType.AddProperty(
			"Id",
			typeof(string),
			propertyInfo: typeof(Playset).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			afterSaveBehavior: PropertySaveBehavior.Throw);
		id.AddAnnotation("Relational:ColumnName", "id");
		id.AddAnnotation("Relational:ColumnType", "char(36)");

		var author = runtimeEntityType.AddProperty(
			"Author",
			typeof(string),
			propertyInfo: typeof(Playset).GetProperty("Author", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<Author>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			valueGenerated: ValueGenerated.OnAdd);
		author.AddAnnotation("Relational:ColumnName", "author");
		author.AddAnnotation("Relational:ColumnType", "varchar(255)");
		author.AddAnnotation("Relational:DefaultValue", "");

		var createdOn = runtimeEntityType.AddProperty(
			"CreatedOn",
			typeof(long),
			propertyInfo: typeof(Playset).GetProperty("CreatedOn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<CreatedOn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			sentinel: 0L);
		createdOn.AddAnnotation("Relational:ColumnName", "createdOn");
		createdOn.AddAnnotation("Relational:ColumnType", "datetime");

		var description = runtimeEntityType.AddProperty(
			"Description",
			typeof(string),
			propertyInfo: typeof(Playset).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true,
			valueGenerated: ValueGenerated.OnAdd);
		description.AddAnnotation("Relational:ColumnName", "description");
		description.AddAnnotation("Relational:ColumnType", "varchar(255)");
		description.AddAnnotation("Relational:DefaultValue", "");

		var hasNotApprovedChanges = runtimeEntityType.AddProperty(
			"HasNotApprovedChanges",
			typeof(bool?),
			propertyInfo: typeof(Playset).GetProperty("HasNotApprovedChanges", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<HasNotApprovedChanges>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			valueGenerated: ValueGenerated.OnAdd);
		hasNotApprovedChanges.AddAnnotation("Relational:ColumnName", "hasNotApprovedChanges");
		hasNotApprovedChanges.AddAnnotation("Relational:ColumnType", "boolean");
		hasNotApprovedChanges.AddAnnotation("Relational:DefaultValueSql", "'0'");

		var isActive = runtimeEntityType.AddProperty(
			"IsActive",
			typeof(bool?),
			propertyInfo: typeof(Playset).GetProperty("IsActive", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<IsActive>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		isActive.AddAnnotation("Relational:ColumnName", "isActive");
		isActive.AddAnnotation("Relational:ColumnType", "boolean");

		var isRemoved = runtimeEntityType.AddProperty(
			"IsRemoved",
			typeof(bool?),
			propertyInfo: typeof(Playset).GetProperty("IsRemoved", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<IsRemoved>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			valueGenerated: ValueGenerated.OnAdd);
		isRemoved.AddAnnotation("Relational:ColumnName", "isRemoved");
		isRemoved.AddAnnotation("Relational:ColumnType", "boolean");
		isRemoved.AddAnnotation("Relational:DefaultValueSql", "false");

		var lastServerChecksum = runtimeEntityType.AddProperty(
			"LastServerChecksum",
			typeof(string),
			propertyInfo: typeof(Playset).GetProperty("LastServerChecksum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<LastServerChecksum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		lastServerChecksum.AddAnnotation("Relational:ColumnName", "lastServerChecksum");

		var loadOrder = runtimeEntityType.AddProperty(
			"LoadOrder",
			typeof(string),
			propertyInfo: typeof(Playset).GetProperty("LoadOrder", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<LoadOrder>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		loadOrder.AddAnnotation("Relational:ColumnName", "loadOrder");
		loadOrder.AddAnnotation("Relational:ColumnType", "varchar(255)");

		var name = runtimeEntityType.AddProperty(
			"Name",
			typeof(string),
			propertyInfo: typeof(Playset).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
		name.AddAnnotation("Relational:ColumnName", "name");
		name.AddAnnotation("Relational:ColumnType", "varchar(255)");

		var offDisk = runtimeEntityType.AddProperty(
			"OffDisk",
			typeof(bool?),
			propertyInfo: typeof(Playset).GetProperty("OffDisk", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<OffDisk>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			valueGenerated: ValueGenerated.OnAdd);
		offDisk.AddAnnotation("Relational:ColumnName", "offDisk");
		offDisk.AddAnnotation("Relational:ColumnType", "boolean");
		offDisk.AddAnnotation("Relational:DefaultValueSql", "'0'");

		var owned = runtimeEntityType.AddProperty(
			"Owned",
			typeof(bool?),
			propertyInfo: typeof(Playset).GetProperty("Owned", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<Owned>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			valueGenerated: ValueGenerated.OnAdd);
		owned.AddAnnotation("Relational:ColumnName", "owned");
		owned.AddAnnotation("Relational:ColumnType", "boolean");
		owned.AddAnnotation("Relational:DefaultValueSql", "'1'");

		var pdxId = runtimeEntityType.AddProperty(
			"PdxId",
			typeof(int?),
			propertyInfo: typeof(Playset).GetProperty("PdxId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<PdxId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		pdxId.AddAnnotation("Relational:ColumnName", "pdxId");
		pdxId.AddAnnotation("Relational:ColumnType", "INT");

		var pdxUserId = runtimeEntityType.AddProperty(
			"PdxUserId",
			typeof(string),
			propertyInfo: typeof(Playset).GetProperty("PdxUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<PdxUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		pdxUserId.AddAnnotation("Relational:ColumnName", "pdxUserId");
		pdxUserId.AddAnnotation("Relational:ColumnType", "char(36)");

		var ratingsCount = runtimeEntityType.AddProperty(
			"RatingsCount",
			typeof(int),
			propertyInfo: typeof(Playset).GetProperty("RatingsCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<RatingsCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			valueGenerated: ValueGenerated.OnAdd,
			sentinel: 0);
		ratingsCount.AddAnnotation("Relational:ColumnName", "ratingsCount");
		ratingsCount.AddAnnotation("Relational:DefaultValueSql", "'0'");

		var state = runtimeEntityType.AddProperty(
			"State",
			typeof(string),
			propertyInfo: typeof(Playset).GetProperty("State", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<State>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			valueGenerated: ValueGenerated.OnAdd);
		state.AddAnnotation("Relational:ColumnName", "state");
		state.AddAnnotation("Relational:DefaultValue", "private");

		var subscribersCount = runtimeEntityType.AddProperty(
			"SubscribersCount",
			typeof(int),
			propertyInfo: typeof(Playset).GetProperty("SubscribersCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<SubscribersCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			valueGenerated: ValueGenerated.OnAdd,
			sentinel: 0);
		subscribersCount.AddAnnotation("Relational:ColumnName", "subscribersCount");
		subscribersCount.AddAnnotation("Relational:DefaultValueSql", "'0'");

		var syncState = runtimeEntityType.AddProperty(
			"SyncState",
			typeof(string),
			propertyInfo: typeof(Playset).GetProperty("SyncState", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<SyncState>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		syncState.AddAnnotation("Relational:ColumnName", "syncState");
		syncState.AddAnnotation("Relational:ColumnType", "varchar(255)");

		var syncedOn = runtimeEntityType.AddProperty(
			"SyncedOn",
			typeof(DateTime?),
			propertyInfo: typeof(Playset).GetProperty("SyncedOn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<SyncedOn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		syncedOn.AddAnnotation("Relational:ColumnName", "syncedOn");
		syncedOn.AddAnnotation("Relational:ColumnType", "datetime");

		var thumbnailFileUrl = runtimeEntityType.AddProperty(
			"ThumbnailFileUrl",
			typeof(string),
			propertyInfo: typeof(Playset).GetProperty("ThumbnailFileUrl", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<ThumbnailFileUrl>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		thumbnailFileUrl.AddAnnotation("Relational:ColumnName", "thumbnailFileUrl");
		thumbnailFileUrl.AddAnnotation("Relational:ColumnType", "varchar(255)");

		var updatedOn = runtimeEntityType.AddProperty(
			"UpdatedOn",
			typeof(long?),
			propertyInfo: typeof(Playset).GetProperty("UpdatedOn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(Playset).GetField("<UpdatedOn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		updatedOn.AddAnnotation("Relational:ColumnName", "updatedOn");
		updatedOn.AddAnnotation("Relational:ColumnType", "datetime");

		var key = runtimeEntityType.AddKey(
			new[] { id });
		runtimeEntityType.SetPrimaryKey(key);

		var index = runtimeEntityType.AddIndex(
			new[] { pdxId },
			unique: true);

		return runtimeEntityType;
	}

	public static void CreateAnnotations(RuntimeEntityType runtimeEntityType) {
		runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
		runtimeEntityType.AddAnnotation("Relational:Schema", null);
		runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
		runtimeEntityType.AddAnnotation("Relational:TableName", "playsets");
		runtimeEntityType.AddAnnotation("Relational:ViewName", null);
		runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

		Customize(runtimeEntityType);
	}

	static partial void Customize(RuntimeEntityType runtimeEntityType);
}
