// <auto-generated />
using System;
using System.Reflection;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace StlTechRelGen.Db;

[EntityFrameworkInternal]
public partial class PlaysetsModEntityType {
	public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null) {
		var runtimeEntityType = model.AddEntityType(
			"StlTechRelGen.Db.PlaysetsMod",
			typeof(PlaysetsMod),
			baseEntityType,
			propertyCount: 4,
			navigationCount: 2,
			foreignKeyCount: 2,
			unnamedIndexCount: 2);

		var enabled = runtimeEntityType.AddProperty(
			"Enabled",
			typeof(bool?),
			propertyInfo: typeof(PlaysetsMod).GetProperty("Enabled", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(PlaysetsMod).GetField("<Enabled>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true,
			valueGenerated: ValueGenerated.OnAdd);
		enabled.AddAnnotation("Relational:ColumnName", "enabled");
		enabled.AddAnnotation("Relational:ColumnType", "boolean");
		enabled.AddAnnotation("Relational:DefaultValueSql", "'1'");

		var modId = runtimeEntityType.AddProperty(
			"ModId",
			typeof(string),
			propertyInfo: typeof(PlaysetsMod).GetProperty("ModId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(PlaysetsMod).GetField("<ModId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
		modId.AddAnnotation("Relational:ColumnName", "modId");
		modId.AddAnnotation("Relational:ColumnType", "char(36)");

		var playsetId = runtimeEntityType.AddProperty(
			"PlaysetId",
			typeof(string),
			propertyInfo: typeof(PlaysetsMod).GetProperty("PlaysetId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(PlaysetsMod).GetField("<PlaysetId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
		playsetId.AddAnnotation("Relational:ColumnName", "playsetId");
		playsetId.AddAnnotation("Relational:ColumnType", "char(36)");

		var position = runtimeEntityType.AddProperty(
			"Position",
			typeof(int?),
			propertyInfo: typeof(PlaysetsMod).GetProperty("Position", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(PlaysetsMod).GetField("<Position>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			nullable: true);
		position.AddAnnotation("Relational:ColumnName", "position");

		var index = runtimeEntityType.AddIndex(
			new[] { modId });

		var index0 = runtimeEntityType.AddIndex(
			new[] { playsetId });

		return runtimeEntityType;
	}

	public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType) {
		var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ModId") },
			principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
			principalEntityType,
			deleteBehavior: DeleteBehavior.Cascade,
			required: true);

		var mod = declaringEntityType.AddNavigation("Mod",
			runtimeForeignKey,
			onDependent: true,
			typeof(Mod),
			propertyInfo: typeof(PlaysetsMod).GetProperty("Mod", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(PlaysetsMod).GetField("<Mod>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

		return runtimeForeignKey;
	}

	public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType) {
		var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("PlaysetId") },
			principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
			principalEntityType,
			deleteBehavior: DeleteBehavior.Cascade,
			required: true);

		var playset = declaringEntityType.AddNavigation("Playset",
			runtimeForeignKey,
			onDependent: true,
			typeof(Playset),
			propertyInfo: typeof(PlaysetsMod).GetProperty("Playset", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
			fieldInfo: typeof(PlaysetsMod).GetField("<Playset>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

		return runtimeForeignKey;
	}

	public static void CreateAnnotations(RuntimeEntityType runtimeEntityType) {
		runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
		runtimeEntityType.AddAnnotation("Relational:Schema", null);
		runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
		runtimeEntityType.AddAnnotation("Relational:TableName", "playsets_mods");
		runtimeEntityType.AddAnnotation("Relational:ViewName", null);
		runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

		Customize(runtimeEntityType);
	}

	static partial void Customize(RuntimeEntityType runtimeEntityType);
}
