name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Configure Git line endings
        run: git config --global core.autocrlf input

      - uses: actions/checkout@v7

      - uses: actions/setup-dotnet@v5

      - name: Restore dependencies
        run: dotnet restore

      - name: Get version
        id: version
        run: |
          VERSION=$(dotnet build StlTechRelGen -getProperty:Version)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Version: $VERSION"

      - name: Check formatting
        run: dotnet format --verify-no-changes

      - name: Build
        run: dotnet build -c Release
